all: add item list del match year edit ui

add: ccadd.c
	gcc -o ccadd ccadd.c -Wall -Werror -Wpedantic

item: ccitem.c
	gcc -o ccitem ccitem.c -Wall -Werror -Wpedantic

list: cclist.c
	gcc -o cclist cclist.c -Wall -Werror -Wpedantic

del: ccdel.c
	gcc -o ccdel ccdel.c -Wall -Werror -Wpedantic

match: ccmatch.c
	gcc -o ccmatch ccmatch.c -Wall -Werror -Wpedantic

year: ccyear.c
	gcc -o ccyear ccyear.c -Wall -Werror -Wpedantic

edit: ccedit.c
	gcc -o ccedit ccedit.c -Wall -Werror -Wpedantic

ui: ccui.c
	gcc -o ccui ccui.c -Wall -Werror -Wpedantic

clean:
	rm *.o ccitem cclist ccdel ccmatch ccyear ccedit ccui
