all: add item list del match year edit

add: ccadd.c
	gcc -o add ccadd.c -Wall -Werror -Wpedantic

item: ccitem.c
	gcc -o item ccitem.c -Wall -Werror -Wpedantic

list: cclist.c
	gcc -o list cclist.c -Wall -Werror -Wpedantic

del: ccdel.c
	gcc -o del ccdel.c -Wall -Werror -Wpedantic

match: ccmatch.c
	gcc -o match ccmatch.c -Wall -Werror -Wpedantic

year: ccyear.c
	gcc -o year ccyear.c -Wall -Werror -Wpedantic

edit: ccedit.c
	gcc -o edit ccedit.c -Wall -Werror -Wpedantic

clean:
	rm *.o item list del match year
